M_13_DjangoCaching/homework/blogs/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import ShowBlogs, create_blog, BlogDetail, SendMessage, BlogerProfile


app_name = "blogs"
urlpatterns = [
    path("", ShowBlogs.as_view(), name="show_blogs"),
    path("to_shop/", RedirectView.as_view(url='/shopapp/', permanent=True), name="to_shop"),
    path("to_login/", RedirectView.as_view(url='login', permanent=True), name="to_login"),
    path("detail_blog/<int:pk>/", BlogDetail.as_view(), name="blog_detail"),
    path("user/<int:pk>/", ShowBlogs.as_view(), name="show_blogs"),
    path("create/", create_blog, name="created_blog"),
    path("send_message/", SendMessage.as_view(), name="send_message"),
    path("profile/<int:pk>/", BlogerProfile.as_view(), name="bloger_profile"),
]

M_13_DjangoCaching/homework/blogs/models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from PIL import Image


def get_upload_path_by_posts(instance, filename):
    return os.path.join('post_images/', now().date().strftime("%Y/%m/%d"), filename)


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'), blank=True)
    created_by = models.ForeignKey(User, verbose_name=_('Created by'), related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created date'))

    def __str__(self):
        return "Post {title}".format(title=self.title)

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ["title", "description"]


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='posts', verbose_name=_('Post'))
    image = models.FileField(upload_to=get_upload_path_by_posts, blank=True, verbose_name=_('Files post'))

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 850 or img.width > 450:
            img.thumbnail((850, 450))
        img.save(self.image.path, quality=70, optimize=True)

    def __str__(self):
        return "PostImage {image}".format(image=self.image)

    class Meta:
        verbose_name = _("PostImage")
        verbose_name_plural = _("PostImages")
        ordering = ["post"]

M_13_DjangoCaching/homework/blogs/forms.py
from django.forms.models import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Post, PostImage


class PostForm(ModelForm):
    title = forms.CharField(
        label=_("Title"),
        required=True,
        widget=forms.TextInput(attrs={})
    )
    description = forms.FileField(
        label=_("Post"),
        required=False,
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 20})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].help_text = ''

    class Meta:
        model = Post
        fields = ["title", "description", ]


class PostImageForm(ModelForm):
    images = forms.FileField(
        label=_("Image post"),
        required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = PostImage
        fields = ["images", ]


class SendMessageForm(forms.Form):
    first_name = forms.CharField(
        label=_('First name*'),
        max_length=100,
        widget=forms.TextInput(),
        required=True
    )
    email = forms.EmailField(
        label=_("Email*"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
        required=True
    )
    phone = forms.CharField(
        label=_('Phone*'),
        max_length=20,
        widget=forms.TextInput(
            attrs={
                "type": "tel",
            },
        ),
        required=True
    )
    message = forms.CharField(
        label=_('Message*'),
        widget=forms.Textarea,
        max_length=2000,
        required=True,
    )

M_13_DjangoCaching/homework/blogs/views.py
from typing import List

from django.contrib.auth.models import User
from django.forms import HiddenInput, modelformset_factory
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, View, DetailView, FormView
from .forms import PostForm, PostImageForm, SendMessageForm
from .models import Post, PostImage


class ShowBlogs(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        print(7777777777)
        user_id = self.kwargs.get('pk')

        if user_id:
            posts = [p for p in Post.objects.filter(created_by_id=user_id)]
            context = {
                "posts": posts
            }
        else:
            posts = [p for p in Post.objects.all()]
            context = {
                'posts': posts
            }

        return render(request, 'blogs/blogs_list.html', context=context)


class BlogDetail(DetailView):
    model = PostImage
    context_object_name = "posts"
    template_name = 'blogs/blogs_detail.html'

    def get_object(self, queryset=None):
        queryset = Post.objects.filter(pk=self.kwargs['pk'])
        return super().get_object(queryset)


@login_required
def create_blog(request: HttpRequest):
    ImageFormSet = modelformset_factory(PostImage, form=PostImageForm, extra=3)
    if request.method == "POST":
        post_form = PostForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES, queryset=PostImage.objects.none())

        if post_form.is_valid() and formset.is_valid():
            new_post = Post(created_by=request.user)
            new_post.title = post_form.cleaned_data['title']
            new_post.description = post_form.cleaned_data['description']
            print(8888888, new_post.pk, request.user.pk)
            # new_post.create_by = request.user.pk
            new_post.save()
            for form in formset.cleaned_data:
                if form:
                    image = form['images']
                    photo = PostImage(post=new_post, image=image)
                    photo.save()
            messages.success(request, "Posted!")
            return redirect('blogs:show_blogs')
        else:
            print(post_form.errors, formset.errors)
    else:
        post_form = PostForm()
        formset = ImageFormSet(queryset=PostImage.objects.none())

    return render(request, 'blogs/created_post.html', context={'form': post_form, 'formset': formset})


class SendMessage(View):
    form_class = SendMessageForm
    template_name = "blogs/contact.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})


class BlogerProfile(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        return render(request, 'blogs/bloger_profile.html', context={"user": user})

M_13_DjangoCaching/homework/blogs/templates/blogs/bloger_profile.html
{% extends "blogs/blogs.html" %}
{% load static %}
{% load i18n %}

{% block title %}
Bloger profile
{% endblock %}

{% block article %}
{% if request.user.is_authenticated %}
<div class="container col-lg-4 mb-5">
    <h5 class="text-center py-4 text-primary">{% trans 'Profile' %}</h5>
    <div class="form-control py-4 px-4 border-primary border-1 d-flex flex-column justify-content-center col-md-12 col-lg-offset-3"
         style="">
        {% if user.profiles.avatar %}
        <img class="img-fluid m-auto rounded-circle" src="{{ user.profiles.avatar.url }}" height=100 width=100 style="border:4px solid #d3232e;"><br><br>
        {% else %}
        <img class="img-fluid m-auto rounded-circle" src="{% static 'default_avatars.png' %}" height=100
             width=100 style="border:1px solid #d3232e;"><br><br>
        {% endif %}
        <div class="product__desc-info">
            <ul class="tab-pane">
            <li>
                 <h6 class="">{% trans 'Username:' %}</h6> <span class="mx-auto"> {{ user.username }} </span>
            </li>
            <li>
                <h6> {% trans 'Email:' %}</h6> <span class="mx-auto">{{ user.email }} </span>
            </li>
        </ul>
        </div>


    </div>
</div>
{% else %}
<h5>{% trans 'You are not identified!' %}</h5>
{% endif%}
{% endblock %}

M_13_DjangoCaching/homework/blogs/templates/blogs/blogs_detail.html
{% extends 'blogs/blogs.html' %}
{% load static %}
{% load i18n %}

{% block title %}
AllPost list
{% endblock %}

{% block article %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-xxl-12">
            <div class="breadcrumb__wrapper">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'shopapp:shop_page' %}">{% trans 'Home' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Post detail' %}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="news-detalis-content">
    <ul class="blog-meta">
        <li><a href="blog-details.html"><i class="fal fa-eye"></i>100 Views</a></li>
        <li><a href="blog-details.html"><i class="fal fa-comments"></i> 30 Comments</a></li>
        <li><a href="blog-details.html"><i class="fal fa-calendar-alt"></i>{{ object.created_at }}</a></li>
    </ul>
    <p class="mt-15">{{ object.title }}</p>
    <div class="news-thumb mt-15">
        {% for image in object.posts.all %}
        <img class="img-fluid mb-2" src="{{ image.image.url }}"
             style="object-fit: contain; border-radius: 15px;"
             alt="post_image"/>
        {% endfor %}
    </div>
    <p class="mt-25 mb-50">{{ object.description }}</p>

    <div class="">

        <h6 class="d-inline">

            <a href="{% url 'blogs:bloger_profile' object.created_by.pk %}">
                <img class="img-fluid mb-2 d-inline" src="{{ object.created_by.profiles.avatar.url }}"
                 style="width: 33px; height: 33px; object-fit: contain; border-radius: 15px;"
                 alt="post_image"/>
                {{ object.created_by.first_name }} {{ object.created_by.last_name }}
            </a>

        </h6>
    </div>


    <div class="post-comment-form mt-20">
        <h4 class="post-comment-form-title mb-40">Post Comment</h4>
        <form action="#">
            <div class="input-field">
                <i class="fal fa-pencil-alt"></i>
                <textarea name="comment" id="comment" placeholder="Type your comments...."></textarea>
            </div>
            <div class="input-field">
                <i class="fal fa-user"></i>
                <input type="text" placeholder="Type your name....">
            </div>
            <div class="input-field">
                <i class="fal fa-envelope"></i>
                <input type="text" placeholder="Type your email....">
            </div>
            <div class="input-field">
                <i class="fal fa-globe"></i>
                <input type="text" placeholder="Type your website....">
            </div>
            <button class="post-comment shutter-btn"><i class="fal fa-comments"></i>Post
                Comment
            </button>
        </form>
    </div>
</div>


{% endblock %}

M_13_DjangoCaching/homework/blogs/templates/blogs/blogs_list.html
{% extends 'blogs/blogs.html' %}
{% load static %}
{% load i18n %}


{% block article %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-xxl-12">
            <div class="breadcrumb__wrapper">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'shopapp:shop_page' %}">{% trans 'Home' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Posts' %}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
{% for post in posts %}

<div class="col-xl-6">
    <div class="single-smblog mb-30">
        <div class="smblog-thum">
            <div class="blog-image w-img">
                <a href=""><img src="{{ post.posts.first.image.url }}" alt=""></a>
            </div>
<!--            <div class="blog-tag blog-tag-2">-->
<!--                <a href=""></a>-->
<!--            </div>-->
        </div>
        <div class="smblog-content smblog-content-3">

            <h6><a href="{% url 'blogs:blog_detail' pk=post.pk %}">{{ post.title|truncatechars:100 }}</a></h6>
            <span class="author mb-10">
                posted by
                <a href="{% url 'blogs:bloger_profile' post.created_by.pk %}">
                    {{ post.created_by.first_name }} {{ post.created_by.last_name }}
                </a>
            </span>
            <p>{{ post.description|truncatechars:200 }}</p>
            <div class="smblog-foot pt-15">
                <div class="post-readmore">
                    <a href="{% url 'blogs:blog_detail' pk=post.pk %}"> Read More <span class="icon"></span></a>
                </div>
                <div class="post-date">
                    <a href="">{{ post.created_at }}</a>
                </div>
            </div>
        </div>
    </div>

</div>
{% endfor %}

<div class="row">
    <div class="col-xl-12">
        <div class="basic-pagination text-center pt-30 pb-30">
            <nav>
                <ul>
                    <li>
                        <a href="" class="active">1</a>
                    </li>
                    <li>
                        <a href="">2</a>
                    </li>
                    <li>
                        <a href="">3</a>
                    </li>
                    <li>
                        <a href="">5</a>
                    </li>
                    <li>
                        <a href="">6</a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fal fa-angle-double-right"></i>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
</div>
{% endblock %}

M_13_DjangoCaching/homework/blogs/templates/blogs/created_post.html
{% extends 'blogs/blogs.html' %}
{% load i18n %}

{% block title %}
CreatePost
{% endblock %}

{% block article %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-xxl-12">
            <div class="breadcrumb__wrapper">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'shopapp:shop_page' %}">{% trans 'Home' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Create post' %}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<article>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-6 mx-auto my-5">
                <form class="form-control" method="post" action=""
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {% for field in form %}
                        <div class="d-flex justify-content-between">
                            <p class="" style="">{{ field.label_tag }}</p>
                            <p class="" style="">{{ field }}</p>
                        </div>
                        {% endfor %}
                    </fieldset>
                                        {{ formset.management_form }}
                    {% for form_img in formset %}

                        <p class="d-flex justify-content-between" style="">{{ form_img.label_tag }} {{ form_img }}</p>

                    {% endfor %}
                    <input class="btn btn-primary" type="submit" value="{% trans 'Add' %}">
                </form>
            </div>
        </div>
    </div>
</article>
{% endblock %}