M_09_RegistrationAndAuthorization/homework/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "price"]

    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', blank=True)
    attributes = models.JSONField(default=dict, blank=True, verbose_name='Атрибуты')
    created_by = models.ForeignKey(User, verbose_name='Кем создан', on_delete=models.CASCADE, null=True)
    rating = models.FloatField(verbose_name='Рейтинг', blank=True, default=0.0)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='images', verbose_name='Изображение продукта',
                              default='images/default_image.jpg')
    discount = models.SmallIntegerField(default=0, verbose_name='Процентаная скидка')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    products_count = models.IntegerField(verbose_name='Количество')
    archived = models.BooleanField(default=False, verbose_name='Статус')

    @property
    def description_short(self):
        if len(self.description) < 50:
            return self.description
        return self.description[:48] + "..."

    def __str__(self):
        return self.name


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    promocode = models.CharField(max_length=20, null=False, blank=True, verbose_name='Промокод')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Пользователь')
    products = models.ManyToManyField(
        Product,
        related_name="orders",
        limit_choices_to={"archived": False},
        verbose_name='Продукты'
    )

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

M_09_RegistrationAndAuthorization/homework/shopapp/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse, reverse_lazy
from django.forms import HiddenInput
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from PIL import Image

from .models import Product, Order
from .forms import OrderModelForm, ProductModelForm, ContactForm


class ShopPage(View):

    def get(self, request: HttpRequest):
        context = {"products": Product.objects.filter(archived=False)}
        return render(request, 'shopapp/main.html', context=context)


class ProductList(ListView):
    # model = Product
    context_object_name = "products"
    template_name = 'shopapp/users-list.html'
    queryset = Product.objects.filter(archived=False)


class DetailProduct(DetailView):
    form_class = ProductModelForm
    context_object_name = "products"
    template_name = 'shopapp/product_detail.html'

    def get_queryset(self):
        queryset = Product.objects.filter(pk=self.kwargs['pk'])
        return queryset


class ArchivedProduct(LoginRequiredMixin, DeleteView):
    model = Product
    context_object_name = "products"
    template_name = 'shopapp/product_archived.html'

    def get_success_url(self):
        return reverse_lazy(
            "shopapp:products_list",
        )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super().post(request, *args, **kwargs)


class CreateProduct(LoginRequiredMixin, CreateView):
    # model = Product
    form_class = ProductModelForm
    template_name = 'shopapp/create_product.html'
    success_url = reverse_lazy("shopapp:products_list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['created_by'].widget = HiddenInput()
        return form

    def get_initial(self):
        self.initial['created_by'] = self.request.user.id
        return self.initial

    # def form_valid(self, form):
    #     # form = super().get_form(form)
    #     form.instance.created_by = self.request.user
    #     return super().get_form(form)


class UpdateProduct(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    form_class = ProductModelForm
    template_name = 'shopapp/update_product.html'

    def get_success_url(self):
        return reverse(
            "shopapp:product_detail",
            kwargs={"pk": self.object.pk},
        )

    def get_queryset(self):
        queryset = Product.objects.filter(pk=self.kwargs['pk'])
        return queryset

    def test_func(self):
        product = Product.objects.get(pk=self.kwargs['pk'])
        # self.request.user.groups.filter(name='Edit').exists()
        return self.request.user.is_superuser or self.request.user == product.created_by


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = "orders"
    template_name = 'shopapp/orders-list.html'


class OrderCreate(LoginRequiredMixin, CreateView):
    form_class = OrderModelForm
    template_name = 'shopapp/create_order.html'

    def get_success_url(self):
        return reverse(
            "shopapp:orders_user",
            kwargs={"pk": self.request.user.pk},
        )

    def get_initial(self):
        return {'user': self.request.user}


class OrderListByUser(LoginRequiredMixin, ListView):
    model = OrderModelForm
    context_object_name = "orders"
    template_name = 'shopapp/orders-list.html'

    def get_queryset(self):
        queryset = Order.objects.select_related("user").prefetch_related("products").filter(
            user=self.kwargs['pk']).all()

        return queryset


class UpdateOrder(LoginRequiredMixin, UpdateView):
    model = Order
    template_name = 'shopapp/update_order.html'
    fields = ["promocode", "delivery_address", "user", "products"]

    def get_success_url(self):
        return reverse(
            "shopapp:order_detail",
            kwargs={"pk": self.object.pk},
        )

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['user'].widget = HiddenInput()
        return form


class OrderDetail(LoginRequiredMixin, DetailView):
    # model = Order
    context_object_name = "orders"
    template_name = 'shopapp/order_detail.html'
    queryset = Order.objects.select_related("user").prefetch_related("products").all()


class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    context_object_name = "orders"
    template_name = 'shopapp/delete_order.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy(
            "shopapp:orders_list",
        )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super().post(request, *args, **kwargs)


class Contact(View):
    form_class = ContactForm
    template_name = "shopapp/contact.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

M_09_RegistrationAndAuthorization/homework/shopapp/templates/shopapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="https://otkorobki.ru/favicon.svg" type="image/svg+xml">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<main class="bg-info" style="min-height: 40vw;">
    <header class="bg-dark">
        <div class="container">
            <div class="navbar navbar-expand-sm px-0">
                <div class="container-fluid">
                    <a class="navbar-brand text-white" href="#">Global</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarScroll">
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll justify-content-between"
                            style="--bs-scroll-height: 100px;">

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'shopapp:shop_page' %}"> Главная </a>
                            </li>
                            {% if perms.shopapp.change_product or request.user.is_superuser %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle mx-3" id="Preview" href="#" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Продукты
                                </a>
                                <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="Preview">
                                    <a class="nav-link text-black" href="{% url 'shopapp:create_product' %}"> Добавить </a>
                                    <a class="nav-link" href="{% url 'shopapp:products_list' %}"> Прайс </a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="Preview-order" href="#" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Заказы
                                </a>
                                <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="Preview-order">
                                    <a class="dropdown-item" href="{% url 'shopapp:create_order' %}">Добавить </a>
                                    <a class="dropdown-item" href="{% url 'shopapp:orders_user' pk=request.user.pk %}">
                                        Просмотреть заказы
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item"><a class="nav-link mx-3" href="{% url 'shopapp:contact' %}">
                                Контакты </a>
                            </li>
                            {% endif %}
                        </ul>
                        {% if perms.shopapp.change_product or request.user.is_superuser %}
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:profile' %}">
                                    <i class="fa fa-user fa-2x text-primary"></i>
                                </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll align-items-center">
                            <li class="nav-item mx-2"><a href="{% url 'logout' %}"
                                                    class="btn btn-primary bg-danger text-white me-3">
                                <i class="fa fa-user"></i> Log Out </a>
                            </li>
                            <li class="nav-item fa fa-shopping-basket fa-2x"
                                style="color: white; opacity: 1.0; text-align: center"><span class="px-2"
                                                                                             style="font-size: 16px;">0 ₽</span>
                            </li>
                        </ul>
                        {% else %}
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll align-items-center" style="">
                            <li class="nav-item"><a class="nav-link" href="{% url 'shopapp:products_list' %}">
                                Прайс </a></li>
                            <li class="nav-item"><a class="nav-link" href="#"> Блог </a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'shopapp:contact' %}"> Контакты </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll align-items-center">
                            <li class="nav-item" style="margin-left: 5vw;">
                                <a class="btn btn-primary text-white me-3" href="{% url 'login' %}">
                                    <i class="fa fa-user"></i>
                                    Log In
                                </a>
                            </li>
                            <li class="nav-item active" style="margin-left: 1vw; margin-right: 1vw;">
                                <a class="btn btn-primary text-white active me-3" href="{% url 'register' %}">
                                    <i class="fa fa-sign-in"></i>
                                    Sign Up
                                </a>
                            </li>
                            <li class="nav-item fa fa-shopping-basket fa-2x"
                                style="color: white; opacity: 1.0; text-align: center"><span class="px-2"
                                                                                             style="font-size: 16px;">100 ₽</span>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section class="section-product container d-flex flex-column">
        {% block section %}
        Base section
        {% endblock %}
    </section>
</main>
<footer class="bg-dark">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center mt-2">
                <h2 class="footer-heading"><a href="#" class="logo text-white">Global</a></h2>
                <div class="menu mb-3">
                    <a class="text-white" href="#">Главная</a>
                    <a class="text-white mx-3" href="#">Прайс</a>
                    <a class="me-3 text-white" href="#">Блог</a>
                    <a class="text-white" href="#">Контакты</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a class="" href="">
                        <i class="fa fa-twitter fa-2x"></i></a>

                    <a class="" href="">
                        <i class="fa fa-facebook fa-2x px-3"></i></a>

                    <a class="" href="">
                        <i class="fa fa-instagram fa-2x"></i></a>

                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-12 text-center">
                    <p class="copyright">
                        <a href="" target="_blank">@Global2023</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

M_09_RegistrationAndAuthorization/homework/shopapp/templates/shopapp/register.html
{% extends "shopapp/base.html" %}
{% block title %}
    Register
{% endblock %}

{% block section %}
{% if not user.is_authenticated %}
<div class="container col-lg-6">
<h5 class="text-center my-3">Регистрация</h5>
    <div class="form-control py-4 bg-light.bg-gradient border-5 d-flex justify-content-center col-md-12 col-lg-offset-3">
        <form class="register-form" method="post" action="{% url 'register' %}">
            {% csrf_token %}
<!--            <table class="form-control p-3">{{ form.as_table }}</table>-->
            {{ form.as_p }}
            <input class="btn-primary" type="submit" value="Зарегистрироваться">
        </form>
    </div>
</div>
{% else %}
<h1 class="text-center">Вы уже зарегистрированы!</h1>
<h5 class="text-center">Чтобы зарегистрировать новый аккаунт, выйдете из текущего.</h5>
{% endif %}
{% endblock %}