M_04_DjangoAdmin/mysite/shopapp/urls.py
from django.urls import path
from . import views

app_name = 'shopapp'
urlpatterns = [
    path('shop/', views.index, name='index'),
    path('product/', views.products, name='products'),
    path('order/', views.orders, name='orders'),
]

M_04_DjangoAdmin/mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование')
    discount = models.PositiveSmallIntegerField(default=0, verbose_name='Процентаная скидка')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    archived = models.BooleanField(default=False, verbose_name='Статус')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Order(models.Model):
    promocode = models.CharField(max_length=20, null=False, blank=True, verbose_name='Промокод')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, related_name="orders")

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return 'Order {}'.format(self.user)

M_04_DjangoAdmin/mysite/shopapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest

from . import models


def index(request: HttpRequest) -> HttpResponse:
    return render(request, 'shopapp/shop.html')


def products(request: HttpRequest) -> HttpResponse:
    product_lst = models.Product.objects.all()
    return render(request, 'shopapp/products.html', {"products": product_lst})


def orders(request: HttpRequest) -> HttpResponse:
    orders = models.Order.objects.select_related("user").prefetch_related("product").all()
    return render(request, 'shopapp/orders.html', {"orders": orders})

M_04_DjangoAdmin/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
Base body
{% endblock %}
<div>
    <p></p>
    Date: {% now 'H:i' %} {% now "Y-m-d" %}
</div>
</body>
</html>

M_04_DjangoAdmin/mysite/shopapp/templates/shopapp/orders.html
{% extends "shopapp/base.html" %}

{% block title %}Заказы{% endblock %}

{% block body %}
<h1>Заказы</h1>
<table>
    {% if orders %}
    <tr>
        <th>Промокод</th>
        <th>Адрес доставки</th>
        <th>Дата заказа</th>
        <th>Пользователь</th>
        <th>Продукты</th>
        <th>Цена за единицу</th>
    </tr>
    {% endif %}
    {% for order in orders %}
    <tr>

        <td>{{ order.promocode }}</td>
        <td>{{ order.delivery_address|title }}</td>
        <td>{{ order.created_at }}</td>
        <td>{{ order.user }}</td>
        <td>
            {% for prod in order.product.all %}
            <p>{{ prod }}</p>
            {% endfor %}
        </td>
        <td>
            {% for prod in order.product.all %}
            <p>{{ prod.price }}</p>
            {% endfor %}
        </td>
    {% empty %}
        No orders here
    {% endfor %}
    </tr>

</table>
{% endblock %}

M_04_DjangoAdmin/mysite/shopapp/templates/shopapp/products.html
{% extends "shopapp/base.html" %}

{% block title %}Продукция{% endblock %}

{% block body %}
<h1>Продукция</h1>
<table>
    {% if products %}
    <tr>
        <th>Наименование продукта</th>
        <th>Описание</th>
        <th>Процент скидки</th>
        <th>Цена</th>
    </tr>
    {% endif %}
    {% for product in products %}
    <tr>

        <td>{{ product.name|title }}</td>
        <td>{{ product.description|title }}</td>
        <td>{{ product.discount }}</td>
        <td>{{ product.price }}</td>
    {% empty %}
        No product here
    {% endfor %}
    </tr>

</table>
{% endblock %}

M_04_DjangoAdmin/mysite/shopapp/templates/shopapp/shop.html
{% extends "shopapp/base.html" %}

{% block title %}Список ссылок{% endblock %}

{% block body %}

<div>
    <ul>
        <li><a href="{% url 'shopapp:products' %}">Продукция</a></li>
        <li><a href="{% url 'shopapp:orders' %}">Заказы</a></li>
    </ul>
</div>


{% endblock %}